# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example ğ‘¥MK'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["cantor"]'
      merge: '["manna-harbour/qmk_firmware/xmk"]'
      alphas: '["colemak"]'
      
